FROM node:18-alpine AS build

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

COPY tsconfig*.json ./

RUN yarn build

FROM node:18-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY package.json yarn.lock ./
RUN yarn install --production

COPY ormconfig.js ./

COPY --from=build /app/dist ./dist

EXPOSE 5000

ENTRYPOINT ["yarn", "start:prod"]
